version: '3.8'

services:
  docker-app:
    build:
      context: ./docker-next
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - ./docker-next:/app
      - /app/node_modules

  docker-fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docker-fastapi
    depends_on:
      - docker-mysql
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/fastapi
          
  docker-influxdb:
    image: influxdb:2.7.5
    container_name: docker-influxdb
    ports:
      - '8888:8086'
    volumes:
      - ./database:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=asszonyij
      - DOCKER_INFLUXDB_INIT_PASSWORD=1234567890
      - DOCKER_INFLUXDB_INIT_ORG=VUT
      - DOCKER_INFLUXDB_INIT_BUCKET=school_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ZqdB328qWerxyD32I6XcWPChj0xixkxcyUQ2-k4TunHzcn7FmSGwCZ93kaHTw1DGVFAC0mH9RU7F_5aCy11yJQ==

  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - '3333:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: auth_users
      MYSQL_USER: asszonyij
      MYSQL_PASSWORD: 1234567890
    volumes:
      - ./users_db:/var/lib/mysql        

  docker-telegraf:
    image: telegraf:latest
    user: 1000:1000
    container_name: docker-telegraf
    ports:
      - 8186:8186
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf:/etc/telegraf:ro
    environment:
      INFLUX_TOKEN: ZqdB328qWerxyD32I6XcWPChj0xixkxcyUQ2-k4TunHzcn7FmSGwCZ93kaHTw1DGVFAC0mH9RU7F_5aCy11yJQ==
      INFLUX_ORG: VUT
      INFLUX_BUCKET: school_data
    depends_on:
      - docker-influxdb
