version: '3.8'

services:
  docker-app:
    build:
      context: ./docker-next
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - ./docker-next:/app
      - /app/node_modules

  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - '3333:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: auth_users
      MYSQL_USER: asszonyij
      MYSQL_PASSWORD: 1234567890
    volumes:
      - ./users_db:/var/lib/mysql


  docker-fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docker-fastapi
    depends_on:
      - docker-mysql
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/fastapi
          
  docker-influxdb:
    image: influxdb:2.7.5
    container_name: docker-influxdb
    ports:
      - '8888:8086'
    volumes:
      - ./database:/var/lib/influxdb2
        # - /etc/ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt
        #- /etc/ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=asszonyij
      - DOCKER_INFLUXDB_INIT_PASSWORD=1234567890
      - DOCKER_INFLUXDB_INIT_ORG=VUT
      - DOCKER_INFLUXDB_INIT_BUCKET=school_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ZqdB328qWerxyD32I6XcWPChj0xixkxcyUQ2-k4TunHzcn7FmSGwCZ93kaHTw1DGVFAC0mH9RU7F_5aCy11yJQ==
        # - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
        # - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key

  docker-telegraf:
    image: telegraf:latest
    user: 1000:1000
    container_name: docker-telegraf
    ports:
      - 8186:8186
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf:/etc/telegraf:ro
        #- /etc/ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt
        #- /etc/ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key
      - /etc/ssl/telegraf.key:/etc/ssl/telegraf.key
      - /etc/ssl/telegraf.cert:/etc/ssl/telegraf.cert

    environment:
      INFLUX_TOKEN: ZqdB328qWerxyD32I6XcWPChj0xixkxcyUQ2-k4TunHzcn7FmSGwCZ93kaHTw1DGVFAC0mH9RU7F_5aCy11yJQ==
      INFLUX_ORG: VUT
      INFLUX_BUCKET: school_data
    depends_on:
      - docker-influxdb

  docker-ntp:
    image: cturra/ntp
    container_name: docker-ntp-server
    restart: unless-stopped
    ports:
      - "123:123/udp"
    environment:
      - NTP_SERVERS=pool.ntp.org
    volumes:
      - ./chrony-data:/var/lib/chrony
    cap_add:
      - SYS_TIME
    network_mode: host

