version: '3.8'
services:
  docker-app:
    build:
      context: ./docker-next
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - ./docker-next:/app
      - /app/node_modules

  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - '3333:3306'
    environment:
      - MYSQL_DATABASE=authusers
    env_file:
      - ./env
    volumes:
      - ./users_db:/var/lib/mysql


  docker-fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docker-fastapi
    depends_on:
      - docker-mysql
    ports:
      - '8000:8000'
    env_file:
      - ./env
    volumes:
      - ./backend:/fastapi
      - /etc/localtime:/etc/localtime:ro
          
  docker-influxdb:
    image: influxdb:2.7.5
    container_name: docker-influxdb
    ports:
      - '8888:8086'
    volumes:
      - ./database:/var/lib/influxdb
      - ./influxdb-init:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret-admin-token
      - TZ=Etc/GMT-2
    env_file:
      - ./env

  docker-telegraf:
    image: telegraf:latest
    user: 1000:1000
    container_name: docker-telegraf
    ports:
      - 8186:8186
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf:/etc/telegraf:ro
      - ./CA/ca.pem:/etc/ssl/ca.pem:ro
      - ./testCA/myCA/private/telegraf.key:/etc/ssl/telegraf.key:ro
      - ./testCA/myCA/certs/telegraf.cert:/etc/ssl/telegraf.cert:ro
      - ./testCA/myCA/ca.crt:/etc/ssl/myCA.crt:ro
    env_file:
      - ./env
    depends_on:
      - docker-influxdb

  docker-ntp:
    image: cturra/ntp
    container_name: docker-ntp
    restart: unless-stopped
    ports:
      - "123:123/udp"
    environment:
      - NTP_SERVERS=pool.ntp.org
    volumes:
      - ./chrony-data:/var/lib/chrony
    cap_add:
      - SYS_TIME
    network_mode: bridge
