version: '3.8'
services:
  docker-app:
    build:
      context: ./docker-next
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - ./docker-next:/app
      - /app/node_modules

  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - '3333:3306'
    env_file:
      - ./env
    volumes:
      - ./users_db1:/var/lib/mysql5


  docker-fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docker-fastapi
    depends_on:
      - docker-mysql
    ports:
      - '8000:8000'
    env_file:
      - ./env
    volumes:
      - ./backend:/fastapi
      - /etc/localtime:/etc/localtime:ro
          
  docker-influxdb:
    image: influxdb:2.7.5
    container_name: docker-influxdb
    ports:
      - '8888:8086'
    volumes:
      - ./database1:/var/lib/influxdb2
    environment:
      #- DOCKER_INFLUXDB_INIT_MODE=setup
      #- DOCKER_INFLUXDB_INIT_USERNAME=asszonyij
      #- DOCKER_INFLUXDB_INIT_PASSWORD=1234567890
      #- DOCKER_INFLUXDB_INIT_ORG=VUT
      #- DOCKER_INFLUXDB_INIT_BUCKET=school_data
      #- NTP_SERVER=docker-ntp
      - TZ=Etc/GMT-2
    env_file:
      - ./env

  docker-telegraf:
    image: telegraf:latest
    user: 1000:1000
    container_name: docker-telegraf
    ports:
      - 8186:8186
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf:/etc/telegraf:ro
      - ./CA/ca.pem:/etc/ssl/ca.pem:ro
      - ./testCA/myCA/private/telegraf.key:/etc/ssl/telegraf.key:ro
      - ./testCA/myCA/certs/telegraf.cert:/etc/ssl/telegraf.cert:ro
      - ./testCA/myCA/ca.crt:/etc/ssl/myCA.crt:ro

        #environment:
      #      INFLUX_TOKEN: ZqdB328qWerxyD32I6XcWPChj0xixkxcyUQ2-k4TunHzcn7FmSGwCZ93kaHTw1DGVFAC0mH9RU7F_5aCy11yJQ==
    env_file:
      - ./env
    depends_on:
      - docker-influxdb

  docker-ntp:
    image: cturra/ntp
    container_name: docker-ntp
    restart: unless-stopped
    ports:
      - "123:123/udp"
    environment:
      - NTP_SERVERS=pool.ntp.org
    volumes:
      - ./chrony-data:/var/lib/chrony
    cap_add:
      - SYS_TIME
    network_mode: bridge
